### RESTClient VSCode scripts
### Note ipf with a spring boot version has as default a fhir prefix, the ipf-tutorials-fhir is without the fhir prefix, iti-65 needs the camel servlet (different prefix camel)

### @host = http://localhost:9091/fhir

@host = http://test.ahdis.ch/fhir


GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+json


### ITI-65 Provide Document Bundle mock call
POST {{host}}/ HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./src/test/resources/mhdch.json

### ITI-66 Find Document Manifests
GET {{host}}/DocumentManifest?status=current&patient.identifier=urn:oid:1.3.6.1.4.1.21367.13.20.2000|IHEGREEN-2601 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

### ITI-67 Find Document References PMP
GET {{host}}/DocumentReference?status=current&patient.identifier=urn:oid:2.999.756.42.2|12345678 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

### ITI-67 Find Document References XDSTools7 ahdis
GET {{host}}/DocumentReference?status=current&patient.identifier=urn:oid:1.3.6.1.4.1.21367.13.20.1000|IHERED-2595 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

### ITI-67 Find Document References XDSTools7 ahdis
GET {{host}}/DocumentReference?status=current&patient.identifier=urn:oid:1.3.6.1.4.1.21367.13.20.3000|IHEBLUE-2611 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

### ITI-66 Find Document Manifest XDSTools7 ahdis
GET {{host}}/DocumentManifest?status=current&patient.identifier=urn:oid:1.3.6.1.4.1.21367.13.20.3000|IHEBLUE-2611 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

### ITI-68 Retrieve Document call
GET http://test.ahdis.ch/camel/xdsretrieve?uniqueId=2.25.68636441871219097345893784144308516188&repositoryUniqueId=1.1.4567332.1.2
Accept: application/fhir+jsonn

### ITI-83 pixm mock call
GET {{host}}/Patient/$ihe-pix?sourceIdentifier=urn:oid:1.2.3.4|0815&targetSystem=urn:oid:1.2.3.4.6 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

### ITI-93 PRIM patient identity feed
POST {{host}}/$process-message HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./src/test/resources/patientfeed.json
