# Specific configuration for the metrics endpoint

spring:
  config:
    activate:
      on-profile: metrics

# https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.exposing
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: ["metrics","prometheus"]
