### Responding Gateway configured
GET http://localhost:9090/fhir/metadata HTTP/1.1
Accept: application/fhir+json

###
GET https://localhost:9091/fhir/metadata HTTP/1.1
Accept: application/fhir+json

### PIXm Query [ITI-78] general (returns 403 when ch-pixm-constraints: true)
GET http://localhost:9090/fhir/Patient/$ihe-pix?sourceIdentifier=urn:oid:1.3.6.1.4.1.12559.11.25.1.19|CHFACILITY900012 HTTP/1.1
Accept: application/fhir+json

### PIXm Query [ITI-78] according to CH PIXm constraints (see https://fhir.ch/ig/ch-epr-fhir/iti-83.html#message-semantics-1)
GET http://localhost:9090/fhir/Patient/$ihe-pix?sourceIdentifier=urn:oid:1.3.6.1.4.1.12559.11.25.1.19|CHFACILITY900012&targetSystem=urn:oid:2.16.756.5.30.1.127.3.10.3&targetSystem=urn:oid:1.3.6.1.4.1.12559.11.20.1 HTTP/1.1
Accept: application/fhir+json

### PDQm Query [ITI-78] according to CH PDQm constraints max 5 resulsts
GET http://localhost:9090/fhir/Patient?family=A HTTP/1.1
Accept: application/fhir+json

### PDQm Query [ITI-78] according to CH PIXm constraints (see https://fhir.ch/ig/ch-epr-fhir/iti-83.html#message-semantics-1)
GET http://localhost:9090/fhir/Patient?family=A HTTP/1.1
Accept: application/fhir+json

### PDQm Query [ITI-78] according to CH PIXm constraints (see https://fhir.ch/ig/ch-epr-fhir/iti-83.html#message-semantics-1)
GET http://localhost:9090/fhir/Patient?family=Mueller HTTP/1.1
Accept: application/fhir+json

### registered also 1.3.6.1.4.1.12559.11.25.1.19 in our repository

### certifactes used are from # certificate from https://ehealthsuisse.ihe-europe.net/gss/certificate/view.seam?id=386
### verify that you have configured in restlcient the certificate for the host (rename der to cer)
###
###      "localhost:9091": {
###        "cert": "/Users/oegger/Documents/github/k8s-fhir.ch/configurations/gazelle-ehealthsuisse/386.cer",
###        "key":  "/Users/oegger/Documents/github/k8s-fhir.ch/configurations/gazelle-ehealthsuisse/386.key"
###      }
### Rest-client: Certificates
### Certificate paths for different hosts. The path can be absolute path or relative path(relative to workspace or current http file)

GET https://localhost:9091/fhir/Patient?identifier=urn:oid:1.3.6.1.4.1.12559.11.25.1.19|PAM8776579876  HTTP/1.1
Accept: application/fhir+json

### EPRS-SPID configured for ahdis xds tools repository   761337610411265304^^^SPID&2.16.756.5.30.1.127.3.10.3&ISO